apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert -f compose.yaml --chart -o kompose-generated
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: data-objects
  name: data-objects
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: data-objects
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert -f compose.yaml --chart -o kompose-generated
        kompose.version: 1.38.0 (a8f5d1cbd)
      labels:
        io.kompose.service: data-objects
    spec:
      containers:
        - env:
            - name: FEED_RELEASE
              value: "24.10"
            - name: KEEP_ALIVE
              value: "1"
          image: registry.community.greenbone.net/community/data-objects
          name: data-objects
          volumeMounts:
            - mountPath: /mnt
              name: data-objects-vol
      restartPolicy: Always
      volumes:
        - name: data-objects-vol
          persistentVolumeClaim:
            claimName: data-objects-vol
