apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert -f compose.yaml --chart -o kompose-generated
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: gsad
  name: gsad
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: gsad
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert -f compose.yaml --chart -o kompose-generated
        kompose.version: 1.38.0 (a8f5d1cbd)
      labels:
        io.kompose.service: gsad
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - env:
            - name: GSAD_API_ONLY
              value: "true"
            - name: GSAD_FOREGROUND
              value: "true"
            - name: GSAD_HTTP_ONLY
              value: "true"
          image: registry.community.greenbone.net/community/gsad:stable
          name: gsad
          volumeMounts:
            - mountPath: /run/gvmd
              name: gvmd-socket-vol
      restartPolicy: Always
      volumes:
        - name: gvmd-socket-vol
          persistentVolumeClaim:
            claimName: gvmd-socket-vol
