apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert -f compose.yaml --chart -o kompose-generated
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: redis-server
  name: redis-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: redis-server
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert -f compose.yaml --chart -o kompose-generated
        kompose.version: 1.38.0 (a8f5d1cbd)
      labels:
        io.kompose.service: redis-server
    spec:
      containers:
        - image: registry.community.greenbone.net/community/redis-server
          name: redis-server
          volumeMounts:
            - mountPath: /run/redis
              name: redis-socket-vol
      restartPolicy: Always
      volumes:
        - name: redis-socket-vol
          persistentVolumeClaim:
            claimName: redis-socket-vol
