apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: scap-data-vol
  name: scap-data-vol
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
