apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-22.4.yml
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.network/greenbone-helm-chart-default: "true"
    io.kompose.service: mqtt-broker
    {{- include "greenbone-ce.labels" . | nindent 4 }}
  name: mqtt-broker
spec:
  containers:
    - image: greenbone/mqtt-broker
      name: mqtt-broker
      ports:
        - containerPort: 1883
          hostPort: 1883
          protocol: TCP
      resources: {}
  restartPolicy: OnFailure

