apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-22.4.yml
    kompose.version: 1.30.0 (9d8dcb518)
  labels:
    io.kompose.service: mqtt-broker
    {{- include "greenbone-ce.labels" . | nindent 4 }}
  name: mqtt-broker
spec:
  ports:
    - name: "1883"
      port: 1883
      targetPort: 1883
  selector:
    io.kompose.service: mqtt-broker
