apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-22.4.yml
    kompose.version: 1.30.0 (9d8dcb518)
  labels:
    io.kompose.network/greenbone-helm-chart-default: "true"
    io.kompose.service: notus-scanner
    {{- include "greenbone-ce.labels" . | nindent 4 }}
  name: notus-scanner
spec:
  containers:
    - env:
        - name: NOTUS_SCANNER_MQTT_BROKER_ADDRESS
          value: mqtt-broker
        - name: NOTUS_SCANNER_PRODUCTS_DIRECTORY
          value: /var/lib/notus/products
      image: greenbone/notus-scanner:stable
      name: notus-scanner
      resources: {}
      volumeMounts:
        - mountPath: /var/lib/notus
          name: notus-data-vol
        - mountPath: /etc/openvas/gnupg
          name: gpg-data-vol
  restartPolicy: OnFailure
  volumes:
    - name: notus-data-vol
      persistentVolumeClaim:
        claimName: notus-data-vol
    - name: gpg-data-vol
      persistentVolumeClaim:
        claimName: gpg-data-vol
