apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: psql-socket-vol
    {{- include "greenbone-ce.labels" . | nindent 4 }}
  name: psql-socket-vol
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
