apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-22.4.yml
    kompose.version: 1.30.0 (9d8dcb518)
  labels:
    io.kompose.network/greenbone-helm-chart-default: "true"
    io.kompose.service: redis-server
    {{- include "greenbone-ce.labels" . | nindent 4 }}
  name: redis-server
spec:
  containers:
    - image: greenbone/redis-server
      name: redis-server
      resources: {}
      volumeMounts:
        - mountPath: /run/redis
          name: redis-socket-vol
  restartPolicy: OnFailure
  volumes:
    - name: redis-socket-vol
      persistentVolumeClaim:
        claimName: redis-socket-vol

